<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Admin\Sell\Catalog\AttributeController' shared service.

$this->services['PrestaShopBundle\\Controller\\Admin\\Sell\\Catalog\\AttributeController'] = $instance = new \PrestaShopBundle\Controller\Admin\Sell\Catalog\AttributeController();

$instance->setContainer($this);

return $instance;
