<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Admin\Sell\Order\CartController' shared service.

$this->services['PrestaShopBundle\\Controller\\Admin\\Sell\\Order\\CartController'] = $instance = new \PrestaShopBundle\Controller\Admin\Sell\Order\CartController();

$instance->setContainer($this);

return $instance;
