<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.extension.alert' shared service.

return $this->services['form.extension.alert'] = new \PrestaShopBundle\Form\Admin\Extension\AlertExtension();
