<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.extension.columns_number' shared service.

return $this->services['form.extension.columns_number'] = new \PrestaShopBundle\Form\Admin\Extension\ColumnsNumberExtension();
