<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.extension.external_link' shared service.

return $this->services['form.extension.external_link'] = new \PrestaShopBundle\Form\Admin\Extension\ExternalLinkExtension();
