<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.sell.product.basic.manufacturer_type' shared service.

return $this->services['form.type.sell.product.basic.manufacturer_type'] = new \PrestaShopBundle\Form\Admin\Sell\Product\Basic\ManufacturerType(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.form.choice_provider.manufacturer_name_by_id']) ? $this->services['prestashop.adapter.form.choice_provider.manufacturer_name_by_id'] : $this->load('getPrestashop_Adapter_Form_ChoiceProvider_ManufacturerNameByIdService.php')) && false ?: '_'});
