<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.contact' shared service.

return $this->services['form.type.contact'] = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\Contact\ContactType(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getLanguages(), ${($_ = isset($this->services['prestashop.bundle.form.data_transformer.default_language_to_filled_array']) ? $this->services['prestashop.bundle.form.data_transformer.default_language_to_filled_array'] : $this->load('getPrestashop_Bundle_Form_DataTransformer_DefaultLanguageToFilledArrayService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.multistore_feature']) ? $this->services['prestashop.adapter.multistore_feature'] : $this->getPrestashop_Adapter_MultistoreFeatureService()) && false ?: '_'}->isUsed());
