<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.address.required_fields' shared service.

return $this->services['form.type.address.required_fields'] = new \PrestaShopBundle\Form\Admin\Sell\Address\RequiredFieldsAddressType(${($_ = isset($this->services['prestashop.core.form.choice_provider.address_required_fields']) ? $this->services['prestashop.core.form.choice_provider.address_required_fields'] : ($this->services['prestashop.core.form.choice_provider.address_required_fields'] = new \PrestaShop\PrestaShop\Core\Form\ChoiceProvider\AddressRequiredFieldsChoiceProvider())) && false ?: '_'});
