<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.reduction' shared service.

return $this->services['form.type.reduction'] = new \PrestaShopBundle\Form\Admin\Type\ReductionType(${($_ = isset($this->services['prestashop.core.form.choice_provider.price_reduction_type']) ? $this->services['prestashop.core.form.choice_provider.price_reduction_type'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_PriceReductionTypeService.php')) && false ?: '_'}->getChoices());
