<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.form_builder_modifier' shared service.

return $this->services['form.form_builder_modifier'] = new \PrestaShopBundle\Form\FormBuilderModifier();
