<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.sell.product.data_transformer.typeahead_redirection_target_transformer' shared service.

return $this->services['form.type.sell.product.data_transformer.typeahead_redirection_target_transformer'] = new \PrestaShopBundle\Form\Admin\Sell\Product\DataTransformer\TypeaheadRedirectionTargetTransformer();
