<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.sell.product.options.suppliers_type' shared service.

return $this->services['form.type.sell.product.options.suppliers_type'] = new \PrestaShopBundle\Form\Admin\Sell\Product\Options\SuppliersType(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getLanguages(), ${($_ = isset($this->services['prestashop.adapter.form.choice_provider.supplier_name_by_id_choice_provider']) ? $this->services['prestashop.adapter.form.choice_provider.supplier_name_by_id_choice_provider'] : ($this->services['prestashop.adapter.form.choice_provider.supplier_name_by_id_choice_provider'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\SupplierNameByIdChoiceProvider())) && false ?: '_'});
