<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.extension.multistore_dropdown' shared service.

return $this->services['form.extension.multistore_dropdown'] = new \PrestaShopBundle\Form\Admin\Extension\MultistoreExtension();
