<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Admin\Improve\Design\MailThemeController' shared service.

$this->services['PrestaShopBundle\\Controller\\Admin\\Improve\\Design\\MailThemeController'] = $instance = new \PrestaShopBundle\Controller\Admin\Improve\Design\MailThemeController();

$instance->setContainer($this);

return $instance;
