<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\Ps_metrics\Controller\Admin\MetricsLegacyStatsController' shared service.

return $this->services['PrestaShop\\Module\\Ps_metrics\\Controller\\Admin\\MetricsLegacyStatsController'] = new \PrestaShop\Module\Ps_metrics\Controller\Admin\MetricsLegacyStatsController();
