<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.command.update_combination_stock_handler' shared service.

return $this->services['prestashop.adapter.product.command.update_combination_stock_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Combination\CommandHandler\UpdateCombinationStockHandler(${($_ = isset($this->services['prestashop.adapter.product.combination.update.combination_stock_updater']) ? $this->services['prestashop.adapter.product.combination.update.combination_stock_updater'] : $this->load('getPrestashop_Adapter_Product_Combination_Update_CombinationStockUpdaterService.php')) && false ?: '_'});
