<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.admin.product_preferences.pagination.data_provider' shared service.

return $this->services['prestashop.admin.product_preferences.pagination.data_provider'] = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\ProductPreferences\PaginationFormDataProvider(${($_ = isset($this->services['prestashop.adapter.product_pagination.configuration']) ? $this->services['prestashop.adapter.product_pagination.configuration'] : $this->load('getPrestashop_Adapter_ProductPagination_ConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
