<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.image.query_handler.get_product_image_handler' shared service.

return $this->services['prestashop.adapter.product.image.query_handler.get_product_image_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Image\QueryHandler\GetProductImageHandler(${($_ = isset($this->services['prestashop.adapter.product.image.repository.product_image_repository']) ? $this->services['prestashop.adapter.product.image.repository.product_image_repository'] : $this->load('getPrestashop_Adapter_Product_Image_Repository_ProductImageRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.product.image.product_image_url_factory']) ? $this->services['prestashop.adapter.product.image.product_image_url_factory'] : $this->load('getPrestashop_Adapter_Product_Image_ProductImageUrlFactoryService.php')) && false ?: '_'});
