<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.command_bus.parser.command_type_parser' shared service.

return $this->services['prestashop.core.command_bus.parser.command_type_parser'] = new \PrestaShop\PrestaShop\Core\CommandBus\Parser\CommandTypeParser();
