<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.combination.command_handler.remove_combination_handler' shared service.

return $this->services['prestashop.adapter.product.combination.command_handler.remove_combination_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Combination\CommandHandler\RemoveCombinationCommandHandler(${($_ = isset($this->services['prestashop.adapter.product.combination.update.combination_remover']) ? $this->services['prestashop.adapter.product.combination.update.combination_remover'] : $this->load('getPrestashop_Adapter_Product_Combination_Update_CombinationRemoverService.php')) && false ?: '_'});
