<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.api.psx.client' shared service.

return $this->services['ps_checkout.api.psx.client'] = new \PrestaShop\Module\PrestashopCheckout\Api\Psx\Client\PsxClient();
