<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.pay_later.configuration' shared service.

return $this->services['ps_checkout.pay_later.configuration'] = new \PrestaShop\Module\PrestashopCheckout\PayPal\PayPalPayLaterConfiguration(${($_ = isset($this->services['ps_checkout.configuration']) ? $this->services['ps_checkout.configuration'] : $this->load('getPsCheckout_ConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.customer']) ? $this->services['ps_checkout.customer'] : $this->load('getPsCheckout_CustomerService.php')) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.merchant']) ? $this->services['ps_checkout.merchant'] : ($this->services['ps_checkout.merchant'] = new \PrestaShop\Module\PrestashopCheckout\Merchant())) && false ?: '_'});
