<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.data.factory.empty_category_decorator' shared service.

return $this->services['prestashop.core.grid.data.factory.empty_category_decorator'] = new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\EmptyCategoryGridDataFactory(${($_ = isset($this->services['prestashop.core.grid.data.factory.empty_category']) ? $this->services['prestashop.core.grid.data.factory.empty_category'] : $this->load('getPrestashop_Core_Grid_Data_Factory_EmptyCategoryService.php')) && false ?: '_'});
