<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.carrier.command_handler.bulk_delete_carrier' shared service.

return $this->services['prestashop.adapter.carrier.command_handler.bulk_delete_carrier'] = new \PrestaShop\PrestaShop\Adapter\Carrier\CommandHandler\BulkDeleteCarrierHandler();
