<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.validator.merchant' shared service.

return $this->services['ps_checkout.validator.merchant'] = new \PrestaShop\Module\PrestashopCheckout\Validator\MerchantValidator(${($_ = isset($this->services['ps_checkout.repository.paypal.account']) ? $this->services['ps_checkout.repository.paypal.account'] : $this->load('getPsCheckout_Repository_Paypal_AccountService.php')) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.repository.prestashop.account']) ? $this->services['ps_checkout.repository.prestashop.account'] : $this->load('getPsCheckout_Repository_Prestashop_AccountService.php')) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.context.prestashop']) ? $this->services['ps_checkout.context.prestashop'] : ($this->services['ps_checkout.context.prestashop'] = new \PrestaShop\Module\PrestashopCheckout\Context\PrestaShopContext())) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.manager.shopuuid']) ? $this->services['ps_checkout.manager.shopuuid'] : ($this->services['ps_checkout.manager.shopuuid'] = new \PrestaShop\Module\PrestashopCheckout\ShopUuidManager())) && false ?: '_'});
