<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.image.product_image_url_factory' shared service.

return $this->services['prestashop.adapter.product.image.product_image_url_factory'] = new \PrestaShop\PrestaShop\Adapter\Product\Image\ProductImagePathFactory(${($_ = isset($this->services['prestashop.adapter.shop.url.product_image_folder_provider']) ? $this->services['prestashop.adapter.shop.url.product_image_folder_provider'] : $this->load('getPrestashop_Adapter_Shop_Url_ProductImageFolderProviderService.php')) && false ?: '_'}->getUrl(), ($this->targetDirs[3].'/img/tmp/'), ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getContext()->language->iso_code);
