<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.image.image_validator' shared service.

return $this->services['prestashop.adapter.image.image_validator'] = new \PrestaShop\PrestaShop\Adapter\Image\ImageValidator(${($_ = isset($this->services['prestashop.core.configuration.upload_size_configuration']) ? $this->services['prestashop.core.configuration.upload_size_configuration'] : $this->load('getPrestashop_Core_Configuration_UploadSizeConfigurationService.php')) && false ?: '_'}->getMaxUploadSizeInBytes());
