<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.combination.command_handler.generate_product_combinations_handler' shared service.

return $this->services['prestashop.adapter.product.combination.command_handler.generate_product_combinations_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Combination\CommandHandler\GenerateProductCombinationsHandler(${($_ = isset($this->services['prestashop.adapter.product.combination.create.combination_creator']) ? $this->services['prestashop.adapter.product.combination.create.combination_creator'] : $this->load('getPrestashop_Adapter_Product_Combination_Create_CombinationCreatorService.php')) && false ?: '_'});
