<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.identifiable_object.builder.combination_form_builder' shared service.

return $this->services['prestashop.core.form.identifiable_object.builder.combination_form_builder'] = ${($_ = isset($this->services['prestashop.core.form.builder.form_builder_factory']) ? $this->services['prestashop.core.form.builder.form_builder_factory'] : $this->load('getPrestashop_Core_Form_Builder_FormBuilderFactoryService.php')) && false ?: '_'}->create('PrestaShopBundle\\Form\\Admin\\Sell\\Product\\Combination\\CombinationFormType', ${($_ = isset($this->services['prestashop.core.form.identifiable_object.data_provider.combination_form_data_provider']) ? $this->services['prestashop.core.form.identifiable_object.data_provider.combination_form_data_provider'] : $this->load('getPrestashop_Core_Form_IdentifiableObject_DataProvider_CombinationFormDataProviderService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.form.identifiable_object.option_provider.combination_form_options_provider']) ? $this->services['prestashop.core.form.identifiable_object.option_provider.combination_form_options_provider'] : ($this->services['prestashop.core.form.identifiable_object.option_provider.combination_form_options_provider'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\OptionProvider\CombinationFormOptionsProvider())) && false ?: '_'});
