<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.provider.command_definition_provider' shared service.

return $this->services['prestashop.core.provider.command_definition_provider'] = new \PrestaShop\PrestaShop\Core\CommandBus\Parser\CommandDefinitionParser();
