<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.tax_rules_group.command_handler.delete_tax_rules_group_handler' shared service.

return $this->services['prestashop.adapter.tax_rules_group.command_handler.delete_tax_rules_group_handler'] = new \PrestaShop\PrestaShop\Adapter\TaxRulesGroup\CommandHandler\DeleteTaxRulesGroupHandler();
