<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.admin.product_preferences.stock.form_handler' shared service.

$this->services['prestashop.admin.product_preferences.stock.form_handler'] = $instance = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\ProductPreferences\ProductPreferencesFormHandler(${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load('getForm_FactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.hook.dispatcher']) ? $this->services['prestashop.core.hook.dispatcher'] : $this->getPrestashop_Core_Hook_DispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.admin.product_preferences.stock.data_provider']) ? $this->services['prestashop.admin.product_preferences.stock.data_provider'] : $this->load('getPrestashop_Admin_ProductPreferences_Stock_DataProviderService.php')) && false ?: '_'}, 'PrestaShopBundle\\Form\\Admin\\Configure\\ShopParameters\\ProductPreferences\\StockType', 'ProductPreferencesPageStock', 'stock');

$instance->setCacheClearer(${($_ = isset($this->services['prestashop.adapter.cache_clearer']) ? $this->services['prestashop.adapter.cache_clearer'] : $this->load('getPrestashop_Adapter_CacheClearerService.php')) && false ?: '_'});

return $instance;
