<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.combination.create.combination_creator' shared service.

return $this->services['prestashop.adapter.product.combination.create.combination_creator'] = new \PrestaShop\PrestaShop\Adapter\Product\Combination\Create\CombinationCreator(${($_ = isset($this->services['prestashop.core.product.combination.generator.combination_generator']) ? $this->services['prestashop.core.product.combination.generator.combination_generator'] : ($this->services['prestashop.core.product.combination.generator.combination_generator'] = new \PrestaShop\PrestaShop\Core\Product\Combination\Generator\CombinationGenerator())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.product.combination.repository.combination_repository']) ? $this->services['prestashop.adapter.product.combination.repository.combination_repository'] : $this->load('getPrestashop_Adapter_Product_Combination_Repository_CombinationRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.product.repository.product_repository']) ? $this->services['prestashop.adapter.product.repository.product_repository'] : $this->load('getPrestashop_Adapter_Product_Repository_ProductRepositoryService.php')) && false ?: '_'});
