<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.command_handler.update_product_seo_handler' shared service.

return $this->services['prestashop.adapter.product.command_handler.update_product_seo_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\CommandHandler\UpdateProductSeoHandler(${($_ = isset($this->services['prestashop.adapter.product.repository.product_repository']) ? $this->services['prestashop.adapter.product.repository.product_repository'] : $this->load('getPrestashop_Adapter_Product_Repository_ProductRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.product.update.product_seo_properties_filler']) ? $this->services['prestashop.adapter.product.update.product_seo_properties_filler'] : $this->load('getPrestashop_Adapter_Product_Update_ProductSeoPropertiesFillerService.php')) && false ?: '_'});
