<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.admin.shipping_preferences.carrier_options.data_provider' shared service.

return $this->services['prestashop.admin.shipping_preferences.carrier_options.data_provider'] = new \PrestaShopBundle\Form\Admin\Improve\Shipping\Preferences\PreferencesCarrierOptionsFormDataProvider(${($_ = isset($this->services['prestashop.adapter.shipping_preferences.carrier_options_configuration']) ? $this->services['prestashop.adapter.shipping_preferences.carrier_options_configuration'] : $this->load('getPrestashop_Adapter_ShippingPreferences_CarrierOptionsConfigurationService.php')) && false ?: '_'});
