<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.performance.optional_features.form_handler' shared service.

return $this->services['prestashop.adapter.performance.optional_features.form_handler'] = new \PrestaShop\PrestaShop\Core\Form\Handler(${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load('getForm_FactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.hook.dispatcher']) ? $this->services['prestashop.core.hook.dispatcher'] : $this->getPrestashop_Core_Hook_DispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.performance.optional_features.form_provider']) ? $this->services['prestashop.adapter.performance.optional_features.form_provider'] : $this->load('getPrestashop_Adapter_Performance_OptionalFeatures_FormProviderService.php')) && false ?: '_'}, 'PrestaShopBundle\\Form\\Admin\\AdvancedParameters\\Performance\\OptionalFeaturesType', 'PerformancePageOptionalFeatures', 'optional_features');
