<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.specific_price.command_handler.add_product_specific_price' shared service.

return $this->services['prestashop.adapter.product.specific_price.command_handler.add_product_specific_price'] = new \PrestaShop\PrestaShop\Adapter\Product\SpecificPrice\CommandHandler\AddProductSpecificPriceHandler(${($_ = isset($this->services['prestashop.adapter.product.specific_price.repository.specific_price_repository']) ? $this->services['prestashop.adapter.product.specific_price.repository.specific_price_repository'] : $this->load('getPrestashop_Adapter_Product_SpecificPrice_Repository_SpecificPriceRepositoryService.php')) && false ?: '_'});
