<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.cart.query_handler.get_last_empty_customer_cart_handler' shared service.

return $this->services['prestashop.adapter.cart.query_handler.get_last_empty_customer_cart_handler'] = new \PrestaShop\PrestaShop\Adapter\Cart\QueryHandler\GetLastEmptyCustomerCartHandler();
