<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.cart.command_handler.update_cart_currency_handler' shared service.

return $this->services['prestashop.adapter.cart.command_handler.update_cart_currency_handler'] = new \PrestaShop\PrestaShop\Adapter\Cart\CommandHandler\UpdateCartCurrencyHandler();
