<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.hook.provider.grid_definition_hook_by_service_ids_provider' shared service.

return $this->services['prestashop.core.hook.provider.grid_definition_hook_by_service_ids_provider'] = new \PrestaShop\PrestaShop\Core\Hook\Provider\GridDefinitionHookByServiceIdsProvider($this);
