<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.news.circuit_breaker.settings' shared service.

$this->services['prestashop.adapter.news.circuit_breaker.settings'] = $instance = new \PrestaShop\CircuitBreaker\FactorySettings(3, 3, 86400);

$instance->setStrippedFailures(3);
$instance->setStrippedTimeout(3);
$instance->setStorage(${($_ = isset($this->services['prestashop.core.circuit_breaker.storage']) ? $this->services['prestashop.core.circuit_breaker.storage'] : $this->load('getPrestashop_Core_CircuitBreaker_StorageService.php')) && false ?: '_'});
$instance->setClientOptions(['method' => 'GET', 'subscribers' => [0 => ${($_ = isset($this->services['prestashop.core.circuit_breaker.guzzle.cache_subscriber']) ? $this->services['prestashop.core.circuit_breaker.guzzle.cache_subscriber'] : $this->load('getPrestashop_Core_CircuitBreaker_Guzzle_CacheSubscriberService.php')) && false ?: '_'}]]);

return $instance;
