<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.file.validator.virtual_product_file_validator' shared service.

return $this->services['prestashop.adapter.file.validator.virtual_product_file_validator'] = new \PrestaShop\PrestaShop\Adapter\File\Validator\VirtualProductFileValidator(${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}->get("PS_ATTACHMENT_MAXIMUM_SIZE"));
