<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.carrier.position_definition' shared service.

return $this->services['prestashop.core.grid.carrier.position_definition'] = new \PrestaShop\PrestaShop\Core\Grid\Position\PositionDefinition('carrier', 'id_carrier', 'position');
