<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.combination.update.combination_remover' shared service.

return $this->services['prestashop.adapter.product.combination.update.combination_remover'] = new \PrestaShop\PrestaShop\Adapter\Product\Combination\Update\CombinationRemover(${($_ = isset($this->services['prestashop.adapter.product.repository.product_repository']) ? $this->services['prestashop.adapter.product.repository.product_repository'] : $this->load('getPrestashop_Adapter_Product_Repository_ProductRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.product.combination.repository.combination_repository']) ? $this->services['prestashop.adapter.product.combination.repository.combination_repository'] : $this->load('getPrestashop_Adapter_Product_Combination_Repository_CombinationRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.product.combination.update.default_combination_updater']) ? $this->services['prestashop.adapter.product.combination.update.default_combination_updater'] : $this->load('getPrestashop_Adapter_Product_Combination_Update_DefaultCombinationUpdaterService.php')) && false ?: '_'});
