<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.util.file_size.size_converter' shared service.

return $this->services['prestashop.core.util.file_size.size_converter'] = new \PrestaShop\PrestaShop\Core\Util\File\FileSizeConverter();
