<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.command_bus.middleware.command_register_middleware' shared service.

return $this->services['prestashop.core.command_bus.middleware.command_register_middleware'] = new \PrestaShop\PrestaShop\Core\CommandBus\Middleware\CommandRegisterMiddleware(${($_ = isset($this->services['tactician.commandbus.default.handler.locator']) ? $this->services['tactician.commandbus.default.handler.locator'] : $this->load('getTactician_Commandbus_Default_Handler_LocatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['tactician.handler.command_name_extractor.class_name']) ? $this->services['tactician.handler.command_name_extractor.class_name'] : ($this->services['tactician.handler.command_name_extractor.class_name'] = new \League\Tactician\Handler\CommandNameExtractor\ClassNameExtractor())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.command_bus.executed_command_registry']) ? $this->services['prestashop.core.command_bus.executed_command_registry'] : $this->load('getPrestashop_Core_CommandBus_ExecutedCommandRegistryService.php')) && false ?: '_'});
