<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Admin\ProductController' shared service.

$this->services['PrestaShopBundle\\Controller\\Admin\\ProductController'] = $instance = new \PrestaShopBundle\Controller\Admin\ProductController();

$instance->setContainer($this);

return $instance;
