<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.command.update_combination_details_handler' shared service.

return $this->services['prestashop.adapter.product.command.update_combination_details_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Combination\CommandHandler\UpdateCombinationDetailsHandler(${($_ = isset($this->services['prestashop.adapter.product.combination.repository.combination_repository']) ? $this->services['prestashop.adapter.product.combination.repository.combination_repository'] : $this->load('getPrestashop_Adapter_Product_Combination_Repository_CombinationRepositoryService.php')) && false ?: '_'});
