<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.command_handler.add_customization_handler' shared service.

return $this->services['prestashop.adapter.command_handler.add_customization_handler'] = new \PrestaShop\PrestaShop\Adapter\Cart\CommandHandler\AddCustomizationHandler();
