<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.currency.repository.currency_repository' shared service.

return $this->services['prestashop.adapter.currency.repository.currency_repository'] = new \PrestaShop\PrestaShop\Adapter\Currency\Repository\CurrencyRepository();
