<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order.refund.updater' shared service.

return $this->services['prestashop.adapter.order.refund.updater'] = new \PrestaShop\PrestaShop\Adapter\Order\Refund\OrderRefundUpdater();
