<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.domain.country.zip_code_format_resolver' shared service.

return $this->services['prestashop.core.domain.country.zip_code_format_resolver'] = new \PrestaShop\PrestaShop\Core\Domain\Country\ZipCodePatternResolver();
