<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.currency.query_handler.get_currency_exchange_rate' shared service.

return $this->services['prestashop.adapter.currency.query_handler.get_currency_exchange_rate'] = new \PrestaShop\PrestaShop\Adapter\Currency\QueryHandler\GetCurrencyExchangeRateHandler(${($_ = isset($this->services['prestashop.core.exchange_rate.provider']) ? $this->services['prestashop.core.exchange_rate.provider'] : $this->load('getPrestashop_Core_ExchangeRate_ProviderService.php')) && false ?: '_'});
