<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.kpi.average_order_value' shared service.

return $this->services['prestashop.adapter.kpi.average_order_value'] = new \PrestaShop\PrestaShop\Adapter\Kpi\AverageOrderValueKpi();
