<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.virtual_product.validate.virtual_product_file_validator' shared service.

return $this->services['prestashop.adapter.product.virtual_product.validate.virtual_product_file_validator'] = new \PrestaShop\PrestaShop\Adapter\Product\VirtualProduct\Validate\VirtualProductFileValidator();
