<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order_return_state.command_handler.add_order_return_state' shared service.

return $this->services['prestashop.adapter.order_return_state.command_handler.add_order_return_state'] = new \PrestaShop\PrestaShop\Adapter\OrderReturnState\CommandHandler\AddOrderReturnStateHandler();
