<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.feature.query_handler.get_feature_for_editing' shared service.

return $this->services['prestashop.adapter.feature.query_handler.get_feature_for_editing'] = new \PrestaShop\PrestaShop\Adapter\Feature\QueryHandler\GetFeatureForEditingHandler();
