<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.cart_rule.command_handler.delete_cart_rule_handler' shared service.

return $this->services['prestashop.adapter.cart_rule.command_handler.delete_cart_rule_handler'] = new \PrestaShop\PrestaShop\Adapter\CartRule\CommandHandler\DeleteCartRuleHandler();
