<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.combination.query_handler.get_combination_suppliers_handler' shared service.

return $this->services['prestashop.adapter.product.combination.query_handler.get_combination_suppliers_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Combination\QueryHandler\GetCombinationSuppliersHandler(${($_ = isset($this->services['prestashop.adapter.product.repository.product_supplier_repository']) ? $this->services['prestashop.adapter.product.repository.product_supplier_repository'] : $this->load('getPrestashop_Adapter_Product_Repository_ProductSupplierRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.product.combination.repository.combination_repository']) ? $this->services['prestashop.adapter.product.combination.repository.combination_repository'] : $this->load('getPrestashop_Adapter_Product_Combination_Repository_CombinationRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.product.repository.product_repository']) ? $this->services['prestashop.adapter.product.repository.product_repository'] : $this->load('getPrestashop_Adapter_Product_Repository_ProductRepositoryService.php')) && false ?: '_'});
