<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.command_handler.add_cart_rule_to_cart_handler' shared service.

return $this->services['prestashop.adapter.command_handler.add_cart_rule_to_cart_handler'] = new \PrestaShop\PrestaShop\Adapter\Cart\CommandHandler\AddCartRuleToCartHandler(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.context_state_manager']) ? $this->services['prestashop.adapter.context_state_manager'] : $this->load('getPrestashop_Adapter_ContextStateManagerService.php')) && false ?: '_'});
