<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.product.combination.generator.combination_generator' shared service.

return $this->services['prestashop.core.product.combination.generator.combination_generator'] = new \PrestaShop\PrestaShop\Core\Product\Combination\Generator\CombinationGenerator();
