<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.combination.validate.combination_validator' shared service.

return $this->services['prestashop.adapter.product.combination.validate.combination_validator'] = new \PrestaShop\PrestaShop\Adapter\Product\Combination\Validate\CombinationValidator();
