<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.attachment.uploader.attachment_file_uploader' shared service.

return $this->services['prestashop.adapter.attachment.uploader.attachment_file_uploader'] = new \PrestaShop\PrestaShop\Adapter\File\Uploader\AttachmentFileUploader(${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.configuration.upload_size_configuration']) ? $this->services['prestashop.core.configuration.upload_size_configuration'] : $this->load('getPrestashop_Core_Configuration_UploadSizeConfigurationService.php')) && false ?: '_'});
