<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order_message.order_message_provider' shared service.

return $this->services['prestashop.adapter.order_message.order_message_provider'] = new \PrestaShop\PrestaShop\Adapter\OrderMessage\OrderMessageProvider(${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getLanguage()->id);
