<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.credit_slip.query_handler.get_credit_slip_ids_by_date_range_handler' shared service.

return $this->services['prestashop.adapter.credit_slip.query_handler.get_credit_slip_ids_by_date_range_handler'] = new \PrestaShop\PrestaShop\Adapter\CreditSlip\QueryHandler\GetCreditSlipIdsByDateRangeHandler();
