<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.administration.notifications.form_provider' shared service.

return $this->services['prestashop.adapter.administration.notifications.form_provider'] = new \PrestaShopBundle\Form\Admin\Configure\AdvancedParameters\Administration\FormDataProvider(${($_ = isset($this->services['prestashop.adapter.notifications.configuration']) ? $this->services['prestashop.adapter.notifications.configuration'] : $this->load('getPrestashop_Adapter_Notifications_ConfigurationService.php')) && false ?: '_'});
