<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.pdf.type_provider.credit_slip' shared service.

return $this->services['prestashop.adapter.pdf.type_provider.credit_slip'] = new \PrestaShop\PrestaShop\Adapter\CreditSlip\CreditSlipTemplateTypeProvider();
