<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'tactician.commandbus.default.middleware.command_handler' shared service.

return $this->services['tactician.commandbus.default.middleware.command_handler'] = new \League\Tactician\Handler\CommandHandlerMiddleware(${($_ = isset($this->services['tactician.handler.command_name_extractor.class_name']) ? $this->services['tactician.handler.command_name_extractor.class_name'] : ($this->services['tactician.handler.command_name_extractor.class_name'] = new \League\Tactician\Handler\CommandNameExtractor\ClassNameExtractor())) && false ?: '_'}, ${($_ = isset($this->services['tactician.commandbus.default.handler.locator']) ? $this->services['tactician.commandbus.default.handler.locator'] : $this->load('getTactician_Commandbus_Default_Handler_LocatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['tactician.handler.method_name_inflector.handle']) ? $this->services['tactician.handler.method_name_inflector.handle'] : ($this->services['tactician.handler.method_name_inflector.handle'] = new \League\Tactician\Handler\MethodNameInflector\HandleInflector())) && false ?: '_'});
