<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Admin\Improve\Modules\UpdatesController' shared service.

$this->services['PrestaShopBundle\\Controller\\Admin\\Improve\\Modules\\UpdatesController'] = $instance = new \PrestaShopBundle\Controller\Admin\Improve\Modules\UpdatesController();

$instance->setContainer($this);

return $instance;
