<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMimhhja\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMimhhja/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMimhhja.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMimhhja\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMimhhja\appProdProjectContainer([
    'container.build_hash' => 'Mimhhja',
    'container.build_id' => '1c336424',
    'container.build_time' => 1672330506,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMimhhja');
