services:
  PrestaShop\Module\PsxMarketingWithGoogle\Tracker\Segment:
    class: 'PrestaShop\Module\PsxMarketingWithGoogle\Tracker\Segment'
    public: true
    arguments:
      - '@psxmarketingwithgoogle.context'
