services:
  PrestaShop\Module\PsxMarketingWithGoogle\Database\Installer:
    class: PrestaShop\Module\PsxMarketingWithGoogle\Database\Installer
    public: true
    arguments:
      - '@psxmarketingwithgoogle'
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Tracker\Segment'
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Handler\ErrorHandler'

  PrestaShop\Module\PsxMarketingWithGoogle\Database\Uninstaller:
    class: PrestaShop\Module\PsxMarketingWithGoogle\Database\Uninstaller
    public: true
    arguments:
      - '@psxmarketingwithgoogle'
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Repository\TabRepository'
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Tracker\Segment'
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Handler\ErrorHandler'
