services:
  PrestaShop\PsAccountsInstaller\Installer\Installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    public: true
    arguments:
      - '3.0.0' # !php/const PrestaShop\Module\PrestashopFacebook\Config\Config::COMPLIANT_PS_ACCOUNTS_VERSION

  PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    public: true
    arguments:
      - '@PrestaShop\PsAccountsInstaller\Installer\Installer'
