services:
  ps_facebook.context:
    class: 'Context'
    public: true
    factory: ['PrestaShop\Module\PrestashopFacebook\Factory\ContextFactory', 'getContext']

  ps_facebook.controller:
    class: 'Controller'
    public: true
    factory: ['PrestaShop\Module\PrestashopFacebook\Factory\ContextFactory', 'getController']

  ps_facebook.cookie:
    class: 'Cookie'
    public: true
    factory: ['PrestaShop\Module\PrestashopFacebook\Factory\ContextFactory', 'getCookie']

  ps_facebook.language:
    class: 'Language'
    public: true
    factory: ['PrestaShop\Module\PrestashopFacebook\Factory\ContextFactory', 'getLanguage']

  ps_facebook.currency:
    class: 'Currency'
    public: true
    factory: ['PrestaShop\Module\PrestashopFacebook\Factory\ContextFactory', 'getCurrency']

  ps_facebook.smarty:
    class: 'Smarty'
    public: true
    factory: ['PrestaShop\Module\PrestashopFacebook\Factory\ContextFactory', 'getSmarty']

  ps_facebook.shop:
    class: 'Shop'
    public: true
    factory: ['PrestaShop\Module\PrestashopFacebook\Factory\ContextFactory', 'getShop']

  ps_facebook.link:
    class: 'Shop'
    public: true
    factory: ['PrestaShop\Module\PrestashopFacebook\Factory\ContextFactory', 'getLink']
