services:
  PrestaShop\Module\PrestashopFacebook\Manager\FbeFeatureManager:
    class: PrestaShop\Module\PrestashopFacebook\Manager\FbeFeatureManager
    public: true
    arguments:
      - '@PrestaShop\Module\PrestashopFacebook\Adapter\ConfigurationAdapter'
      - '@PrestaShop\Module\PrestashopFacebook\API\Client\FacebookClient'
