<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Admin\Sell\Order\ActionsBarButton' shared service.

return $this->services['PrestaShopBundle\\Controller\\Admin\\Sell\\Order\\ActionsBarButton'] = new \PrestaShopBundle\Controller\Admin\Sell\Order\ActionsBarButton();
