<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Admin\Improve\Shipping\CarriersController' shared service.

$this->services['PrestaShopBundle\\Controller\\Admin\\Improve\\Shipping\\CarriersController'] = $instance = new \PrestaShopBundle\Controller\Admin\Improve\Shipping\CarriersController();

$instance->setContainer($this);

return $instance;
