<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Admin\Configure\ShopParameters\ContactsController' shared service.

$this->services['PrestaShopBundle\\Controller\\Admin\\Configure\\ShopParameters\\ContactsController'] = $instance = new \PrestaShopBundle\Controller\Admin\Configure\ShopParameters\ContactsController();

$instance->setContainer($this);

return $instance;
