<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Admin\ErrorController' shared service.

$this->services['PrestaShopBundle\\Controller\\Admin\\ErrorController'] = $instance = new \PrestaShopBundle\Controller\Admin\ErrorController();

$instance->setContainer($this);

return $instance;
