<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.order.update_order_shipping' shared service.

return $this->services['form.type.order.update_order_shipping'] = new \PrestaShopBundle\Form\Admin\Sell\Order\UpdateOrderShippingType(${($_ = isset($this->services['prestashop.adapter.form.choice.provider.carrier_for_order_choice_provider']) ? $this->services['prestashop.adapter.form.choice.provider.carrier_for_order_choice_provider'] : ($this->services['prestashop.adapter.form.choice.provider.carrier_for_order_choice_provider'] = new \PrestaShop\PrestaShop\Adapter\Form\ChoiceProvider\CarrierForOrderChoiceProvider())) && false ?: '_'});
