<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.order.update_order_status' shared service.

return $this->services['form.type.order.update_order_status'] = new \PrestaShopBundle\Form\Admin\Sell\Order\UpdateOrderStatusType(${($_ = isset($this->services['prestashop.core.form.choice_provider.order_state_by_id']) ? $this->services['prestashop.core.form.choice_provider.order_state_by_id'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_OrderStateByIdService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.form.choice_provider.order_state_by_id']) ? $this->services['prestashop.core.form.choice_provider.order_state_by_id'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_OrderStateByIdService.php')) && false ?: '_'}->getChoicesAttributes());
