<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.extension.row_attributes' shared service.

return $this->services['form.extension.row_attributes'] = new \PrestaShopBundle\Form\Admin\Extension\RowAttributesExtension();
