<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.design.theme.import_theme' shared service.

return $this->services['form.type.design.theme.import_theme'] = new \PrestaShopBundle\Form\Admin\Improve\Design\Theme\ImportThemeType(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getLanguages(), ${($_ = isset($this->services['prestashop.core.form.choice_provider.theme_zip']) ? $this->services['prestashop.core.form.choice_provider.theme_zip'] : $this->load('getPrestashop_Core_Form_ChoiceProvider_ThemeZipService.php')) && false ?: '_'}->getChoices());
