<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.date_picker' shared service.

return $this->services['form.type.date_picker'] = new \PrestaShopBundle\Form\Admin\Type\DatePickerType(${($_ = isset($this->services['prestashop.bundle.form.data_transformer.arabic_to_latin_digit']) ? $this->services['prestashop.bundle.form.data_transformer.arabic_to_latin_digit'] : $this->load('getPrestashop_Bundle_Form_DataTransformer_ArabicToLatinDigitService.php')) && false ?: '_'});
