<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.extension.downloadable_file' shared service.

return $this->services['form.extension.downloadable_file'] = new \PrestaShopBundle\Form\Admin\Extension\DownloadFileExtension();
