<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\ArgumentResolver\FiltersBuilderResolver' shared service.

return $this->services['PrestaShopBundle\\Controller\\ArgumentResolver\\FiltersBuilderResolver'] = new \PrestaShopBundle\Controller\ArgumentResolver\FiltersBuilderResolver();
