<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.sell.product.event_listener.feature_value_listener' shared service.

return $this->services['form.type.sell.product.event_listener.feature_value_listener'] = new \PrestaShopBundle\Form\Admin\Sell\Product\EventListener\FeatureValueListener(${($_ = isset($this->services['prestashop.adapter.form.choice_provider.feature_values_choice_provider']) ? $this->services['prestashop.adapter.form.choice_provider.feature_values_choice_provider'] : $this->load('getPrestashop_Adapter_Form_ChoiceProvider_FeatureValuesChoiceProviderService.php')) && false ?: '_'}, ${($_ = isset($this->services['form.form_cloner']) ? $this->services['form.form_cloner'] : ($this->services['form.form_cloner'] = new \PrestaShopBundle\Form\FormCloner())) && false ?: '_'});
