<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.extension.data_list' shared service.

return $this->services['form.extension.data_list'] = new \PrestaShopBundle\Form\Extension\DataListExtension();
