<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.submittable_input' shared service.

return $this->services['form.type.submittable_input'] = new \PrestaShopBundle\Form\Admin\Type\SubmittableInputType();
