<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.sell.product.seo.redirect_option_type' shared service.

return $this->services['form.type.sell.product.seo.redirect_option_type'] = new \PrestaShopBundle\Form\Admin\Sell\Product\SEO\RedirectOptionType(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getLanguages(), ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.router']) ? $this->services['prestashop.router'] : $this->load('getPrestashop_RouterService.php')) && false ?: '_'}, ${($_ = isset($this->services['form.type.sell.product.data_transformer.typeahead_redirection_target_transformer']) ? $this->services['form.type.sell.product.data_transformer.typeahead_redirection_target_transformer'] : ($this->services['form.type.sell.product.data_transformer.typeahead_redirection_target_transformer'] = new \PrestaShopBundle\Form\Admin\Sell\Product\DataTransformer\TypeaheadRedirectionTargetTransformer())) && false ?: '_'});
