<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'finder' shared service.

return $this->services['finder'] = new \Symfony\Component\Finder\Finder();
