<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Admin\Improve\International\GeolocationController' shared service.

$this->services['PrestaShopBundle\\Controller\\Admin\\Improve\\International\\GeolocationController'] = $instance = new \PrestaShopBundle\Controller\Admin\Improve\International\GeolocationController();

$instance->setContainer($this);

return $instance;
