<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsxMarketingWithGoogle\Provider\GoogleTagProvider' shared service.

return $this->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Provider\\GoogleTagProvider'] = new \PrestaShop\Module\PsxMarketingWithGoogle\Provider\GoogleTagProvider();
