<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Admin\Sell\Catalog\MonitoringController' shared service.

$this->services['PrestaShopBundle\\Controller\\Admin\\Sell\\Catalog\\MonitoringController'] = $instance = new \PrestaShopBundle\Controller\Admin\Sell\Catalog\MonitoringController();

$instance->setContainer($this);

return $instance;
