<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.admin.sell.order.credit_slip.credit_slip_options_form_data_provider' shared service.

return $this->services['prestashop.admin.sell.order.credit_slip.credit_slip_options_form_data_provider'] = new \PrestaShopBundle\Form\Admin\Sell\Order\CreditSlip\CreditSlipOptionsFormDataProvider(${($_ = isset($this->services['prestashop.core.credit_slip.credit_slip_options.configuration']) ? $this->services['prestashop.core.credit_slip.credit_slip_options.configuration'] : $this->load('getPrestashop_Core_CreditSlip_CreditSlipOptions_ConfigurationService.php')) && false ?: '_'});
