<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.util.string.string_modifier' shared service.

return $this->services['prestashop.core.util.string.string_modifier'] = new \PrestaShop\PrestaShop\Core\Util\String\StringModifier();
