<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.address.formatter' shared service.

return $this->services['prestashop.adapter.address.formatter'] = new \PrestaShop\PrestaShop\Adapter\Address\AddressFormatter();
