<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.stock.stock_manager' shared service.

return $this->services['prestashop.core.stock.stock_manager'] = new \PrestaShop\PrestaShop\Core\Stock\StockManager();
