<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.sql_manager.command_handler.add_request_sql' shared service.

return $this->services['prestashop.adapter.sql_manager.command_handler.add_request_sql'] = new \PrestaShop\PrestaShop\Adapter\SqlManager\CommandHandler\AddSqlRequestHandler(${($_ = isset($this->services['prestashop.adapter.sql_manager.sql_query_validator']) ? $this->services['prestashop.adapter.sql_manager.sql_query_validator'] : ($this->services['prestashop.adapter.sql_manager.sql_query_validator'] = new \PrestaShop\PrestaShop\Adapter\SqlManager\SqlQueryValidator())) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
