<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order.amount.updater' shared service.

return $this->services['prestashop.adapter.order.amount.updater'] = new \PrestaShop\PrestaShop\Adapter\Order\OrderAmountUpdater(${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.context_state_manager']) ? $this->services['prestashop.adapter.context_state_manager'] : $this->load('getPrestashop_Adapter_ContextStateManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.order.order_detail.updater']) ? $this->services['prestashop.adapter.order.order_detail.updater'] : $this->load('getPrestashop_Adapter_Order_OrderDetail_UpdaterService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.order.product.remover']) ? $this->services['prestashop.adapter.order.product.remover'] : $this->load('getPrestashop_Adapter_Order_Product_RemoverService.php')) && false ?: '_'});
