<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.kpi.net_profit_per_visit' shared service.

return $this->services['prestashop.adapter.kpi.net_profit_per_visit'] = new \PrestaShop\PrestaShop\Adapter\Kpi\NetProfitPerVisitKpi();
