<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.customization.validate.customization_field_validator' shared service.

return $this->services['prestashop.adapter.product.customization.validate.customization_field_validator'] = new \PrestaShop\PrestaShop\Adapter\Product\Customization\Validate\CustomizationFieldValidator();
