<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.command_handler.add_category_to_product_handler' shared service.

return $this->services['prestashop.adapter.product.command_handler.add_category_to_product_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\CommandHandler\AssignProductToCategoryHandler();
