<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.carrier.carrier_module_advice_alert_checker' shared service.

return $this->services['prestashop.adapter.carrier.carrier_module_advice_alert_checker'] = new \PrestaShop\PrestaShop\Adapter\Carrier\CarrierModuleAdviceAlertChecker();
