<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.query_handler.get_related_products_handler' shared service.

return $this->services['prestashop.adapter.product.query_handler.get_related_products_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\QueryHandler\GetRelatedProductsHandler(${($_ = isset($this->services['prestashop.adapter.product.repository.product_repository']) ? $this->services['prestashop.adapter.product.repository.product_repository'] : $this->load('getPrestashop_Adapter_Product_Repository_ProductRepositoryService.php')) && false ?: '_'});
