<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order.command_handler.cancel_order_product_handler' shared service.

return $this->services['prestashop.adapter.order.command_handler.cancel_order_product_handler'] = new \PrestaShop\PrestaShop\Adapter\Order\CommandHandler\CancelOrderProductHandler(${($_ = isset($this->services['prestashop.adapter.order.product_quantity.updater']) ? $this->services['prestashop.adapter.order.product_quantity.updater'] : $this->load('getPrestashop_Adapter_Order_ProductQuantity_UpdaterService.php')) && false ?: '_'}, ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
