<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.command_handler.get_product_is_enabled_handler' shared service.

return $this->services['prestashop.adapter.product.command_handler.get_product_is_enabled_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\QueryHandler\GetProductIsEnabledHandler();
