<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.merchant' shared service.

return $this->services['ps_checkout.merchant'] = new \PrestaShop\Module\PrestashopCheckout\Merchant();
