<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order.command_handler.add_product_to_order_handler' shared service.

return $this->services['prestashop.adapter.order.command_handler.add_product_to_order_handler'] = new \PrestaShop\PrestaShop\Adapter\Order\CommandHandler\AddProductToOrderHandler(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.context_state_manager']) ? $this->services['prestashop.adapter.context_state_manager'] : $this->load('getPrestashop_Adapter_ContextStateManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.order.amount.updater']) ? $this->services['prestashop.adapter.order.amount.updater'] : $this->load('getPrestashop_Adapter_Order_Amount_UpdaterService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.order.product_quantity.updater']) ? $this->services['prestashop.adapter.order.product_quantity.updater'] : $this->load('getPrestashop_Adapter_Order_ProductQuantity_UpdaterService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.order.order_detail.updater']) ? $this->services['prestashop.adapter.order.order_detail.updater'] : $this->load('getPrestashop_Adapter_Order_OrderDetail_UpdaterService.php')) && false ?: '_'});
