<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_metrics.api.analytics' shared service.

return $this->services['ps_metrics.api.analytics'] = new \PrestaShop\Module\Ps_metrics\Api\AnalyticsApi(${($_ = isset($this->services['ps_metrics.api.client.analytics']) ? $this->services['ps_metrics.api.client.analytics'] : $this->load('getPsMetrics_Api_Client_AnalyticsService.php')) && false ?: '_'}, ${($_ = isset($this->services['ps_metrics.helper.config']) ? $this->services['ps_metrics.helper.config'] : $this->load('getPsMetrics_Helper_ConfigService.php')) && false ?: '_'});
