<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.admin.merchandise_return_options.form_data_provider' shared service.

return $this->services['prestashop.admin.merchandise_return_options.form_data_provider'] = new \PrestaShopBundle\Form\Admin\Sell\CustomerService\MerchandiseReturn\MerchandiseReturnOptionsFormDataProvider(${($_ = isset($this->services['prestashop.core.merchandise_return.configuration.merchandise_return_options_configuration']) ? $this->services['prestashop.core.merchandise_return.configuration.merchandise_return_options_configuration'] : $this->load('getPrestashop_Core_MerchandiseReturn_Configuration_MerchandiseReturnOptionsConfigurationService.php')) && false ?: '_'});
