<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.command_handler.update_cart_carrier_handler' shared service.

return $this->services['prestashop.adapter.command_handler.update_cart_carrier_handler'] = new \PrestaShop\PrestaShop\Adapter\Cart\CommandHandler\UpdateCartCarrierHandler(${($_ = isset($this->services['prestashop.adapter.context_state_manager']) ? $this->services['prestashop.adapter.context_state_manager'] : $this->load('getPrestashop_Adapter_ContextStateManagerService.php')) && false ?: '_'});
