<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.grid_factory.empty_category' shared service.

return $this->services['prestashop.core.grid.grid_factory.empty_category'] = new \PrestaShop\PrestaShop\Core\Grid\GridFactory(${($_ = isset($this->services['prestashop.core.grid.definition.factory.monitoring.empty_category']) ? $this->services['prestashop.core.grid.definition.factory.monitoring.empty_category'] : $this->load('getPrestashop_Core_Grid_Definition_Factory_Monitoring_EmptyCategoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.grid.data.factory.empty_category_decorator']) ? $this->services['prestashop.core.grid.data.factory.empty_category_decorator'] : $this->load('getPrestashop_Core_Grid_Data_Factory_EmptyCategoryDecoratorService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.grid.filter.form_factory']) ? $this->services['prestashop.core.grid.filter.form_factory'] : $this->load('getPrestashop_Core_Grid_Filter_FormFactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.hook.dispatcher']) ? $this->services['prestashop.core.hook.dispatcher'] : $this->getPrestashop_Core_Hook_DispatcherService()) && false ?: '_'});
