<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.data.factory.order_decorator' shared service.

return $this->services['prestashop.core.grid.data.factory.order_decorator'] = new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\OrderGridDataFactory(${($_ = isset($this->services['prestashop.core.grid.data.factory.order']) ? $this->services['prestashop.core.grid.data.factory.order'] : $this->load('getPrestashop_Core_Grid_Data_Factory_OrderService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.localization.locale.repository']) ? $this->services['prestashop.core.localization.locale.repository'] : $this->load('getPrestashop_Core_Localization_Locale_RepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getContext()->language->getLocale());
