<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.translation.helper.smarty.smarty_resource_module' shared service.

return $this->services['prestashop.translation.helper.smarty.smarty_resource_module'] = new \PrestaShop\TranslationToolsBundle\Translation\Helper\Smarty\SmartyResourceModule();
