<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.constraint_validator.address_zip_code_validator' shared service.

return $this->services['prestashop.core.constraint_validator.address_zip_code_validator'] = new \PrestaShop\PrestaShop\Core\ConstraintValidator\AddressZipCodeValidator(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.country.country_zip_code_requirements_provider']) ? $this->services['prestashop.adapter.country.country_zip_code_requirements_provider'] : $this->load('getPrestashop_Adapter_Country_CountryZipCodeRequirementsProviderService.php')) && false ?: '_'});
