<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.customization.command_handler.remove_all_customization_fields_from_product_handler' shared service.

return $this->services['prestashop.adapter.product.customization.command_handler.remove_all_customization_fields_from_product_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Customization\CommandHandler\RemoveAllCustomizationFieldsFromProductHandler(${($_ = isset($this->services['prestashop.adapter.product.customization.update.customization_field_deleter']) ? $this->services['prestashop.adapter.product.customization.update.customization_field_deleter'] : $this->load('getPrestashop_Adapter_Product_Customization_Update_CustomizationFieldDeleterService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.product.repository.product_repository']) ? $this->services['prestashop.adapter.product.repository.product_repository'] : $this->load('getPrestashop_Adapter_Product_Repository_ProductRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.product.customization.update.product_customization_field_updater']) ? $this->services['prestashop.adapter.product.customization.update.product_customization_field_updater'] : $this->load('getPrestashop_Adapter_Product_Customization_Update_ProductCustomizationFieldUpdaterService.php')) && false ?: '_'});
