<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.constraint_validator.existing_customer_email_validator' shared service.

return $this->services['prestashop.core.constraint_validator.existing_customer_email_validator'] = new \PrestaShop\PrestaShop\Core\ConstraintValidator\ExistingCustomerEmailValidator(${($_ = isset($this->services['prestashop.adapter.customer.customer_data_source']) ? $this->services['prestashop.adapter.customer.customer_data_source'] : ($this->services['prestashop.adapter.customer.customer_data_source'] = new \PrestaShop\PrestaShop\Adapter\Customer\CustomerDataSource())) && false ?: '_'});
