<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.update.product_indexation_updater' shared service.

return $this->services['prestashop.adapter.product.update.product_indexation_updater'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\ProductIndexationUpdater();
