<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.admin.traffic_seo.meta_settings.shop_urls.form_data_provider' shared service.

return $this->services['prestashop.admin.traffic_seo.meta_settings.shop_urls.form_data_provider'] = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\TrafficSeo\Meta\MetaSettingsShopUrlsFormDataProvider(${($_ = isset($this->services['prestashop.adapter.meta.shop_url.configuration']) ? $this->services['prestashop.adapter.meta.shop_url.configuration'] : $this->load('getPrestashop_Adapter_Meta_ShopUrl_ConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.validate']) ? $this->services['prestashop.adapter.validate'] : ($this->services['prestashop.adapter.validate'] = new \PrestaShop\PrestaShop\Adapter\Validate())) && false ?: '_'});
