<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.specific_price.command_handler.set_global_specific_price_priority_handler' shared service.

return $this->services['prestashop.adapter.product.specific_price.command_handler.set_global_specific_price_priority_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\SpecificPrice\CommandHandler\SetGlobalSpecificPricePriorityHandler(${($_ = isset($this->services['prestashop.adapter.product.specific_price.update.specific_price_priority_updater']) ? $this->services['prestashop.adapter.product.specific_price.update.specific_price_priority_updater'] : ($this->services['prestashop.adapter.product.specific_price.update.specific_price_priority_updater'] = new \PrestaShop\PrestaShop\Adapter\Product\SpecificPrice\Update\SpecificPricePriorityUpdater())) && false ?: '_'});
