<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.form.identifiable_object.currency_form_data_handler' shared service.

return $this->services['prestashop.core.form.identifiable_object.currency_form_data_handler'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataHandler\CurrencyFormDataHandler(${($_ = isset($this->services['prestashop.core.command_bus']) ? $this->services['prestashop.core.command_bus'] : $this->load('getPrestashop_Core_CommandBusService.php')) && false ?: '_'}, [0 => ${($_ = isset($this->services['prestashop.adapter.cache.clearer.symfony_cache_clearer']) ? $this->services['prestashop.adapter.cache.clearer.symfony_cache_clearer'] : ($this->services['prestashop.adapter.cache.clearer.symfony_cache_clearer'] = new \PrestaShop\PrestaShop\Adapter\Cache\Clearer\SymfonyCacheClearer())) && false ?: '_'}, 1 => ${($_ = isset($this->services['prestashop.adapter.cache.clearer.smarty_cache_clearer']) ? $this->services['prestashop.adapter.cache.clearer.smarty_cache_clearer'] : ($this->services['prestashop.adapter.cache.clearer.smarty_cache_clearer'] = new \PrestaShop\PrestaShop\Adapter\Cache\Clearer\SmartyCacheClearer())) && false ?: '_'}]);
