<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.data.factory.attribute_group_decorator' shared service.

return $this->services['prestashop.core.grid.data.factory.attribute_group_decorator'] = new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\AttributeGroupGridDataFactory(${($_ = isset($this->services['prestashop.core.grid.data.factory.attribute_group']) ? $this->services['prestashop.core.grid.data.factory.attribute_group'] : $this->load('getPrestashop_Core_Grid_Data_Factory_AttributeGroupService.php')) && false ?: '_'});
