<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.pdf.generator.credit_slip' shared service.

return $this->services['prestashop.adapter.pdf.generator.credit_slip'] = new \PrestaShop\PrestaShop\Adapter\PDF\PDFGenerator(${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getSmarty(), ${($_ = isset($this->services['prestashop.adapter.pdf.type_provider.credit_slip']) ? $this->services['prestashop.adapter.pdf.type_provider.credit_slip'] : ($this->services['prestashop.adapter.pdf.type_provider.credit_slip'] = new \PrestaShop\PrestaShop\Adapter\CreditSlip\CreditSlipTemplateTypeProvider())) && false ?: '_'});
