<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.language.command_handler.add_language_handler' shared service.

return $this->services['prestashop.adapter.language.command_handler.add_language_handler'] = new \PrestaShop\PrestaShop\Adapter\Language\CommandHandler\AddLanguageHandler(${($_ = isset($this->services['prestashop.adapter.image.image_validator']) ? $this->services['prestashop.adapter.image.image_validator'] : $this->load('getPrestashop_Adapter_Image_ImageValidatorService.php')) && false ?: '_'});
