<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order.order_sibling_provider' shared service.

return $this->services['prestashop.adapter.order.order_sibling_provider'] = new \PrestaShop\PrestaShop\Adapter\Order\OrderSiblingProvider();
