<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.command_handler.set_product_tags_handler' shared service.

return $this->services['prestashop.adapter.product.command_handler.set_product_tags_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\CommandHandler\SetProductTagsHandler(${($_ = isset($this->services['prestashop.adapter.product.repository.product_repository']) ? $this->services['prestashop.adapter.product.repository.product_repository'] : $this->load('getPrestashop_Adapter_Product_Repository_ProductRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.product.updater.product_tag_updater']) ? $this->services['prestashop.adapter.product.updater.product_tag_updater'] : $this->load('getPrestashop_Adapter_Product_Updater_ProductTagUpdaterService.php')) && false ?: '_'});
