<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_metrics.helper.config' shared service.

return $this->services['ps_metrics.helper.config'] = new \PrestaShop\Module\Ps_metrics\Helper\ConfigHelper(${($_ = isset($this->services['ps_metrics.config.env']) ? $this->services['ps_metrics.config.env'] : $this->load('getPsMetrics_Config_EnvService.php')) && false ?: '_'});
