<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.country.query_handler.get_country_required_fields' shared service.

return $this->services['prestashop.adapter.country.query_handler.get_country_required_fields'] = new \PrestaShop\PrestaShop\Adapter\Country\QueryHandler\GetCountryRequiredFieldsHandler(${($_ = isset($this->services['prestashop.adapter.country.country_required_fields_provider']) ? $this->services['prestashop.adapter.country.country_required_fields_provider'] : $this->load('getPrestashop_Adapter_Country_CountryRequiredFieldsProviderService.php')) && false ?: '_'});
