<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.catalog_price_rule.command_handler.get_catalog_price_rule_for_editing_handler' shared service.

return $this->services['prestashop.adapter.catalog_price_rule.command_handler.get_catalog_price_rule_for_editing_handler'] = new \PrestaShop\PrestaShop\Adapter\CatalogPriceRule\QueryHandler\GetCatalogPriceRuleForEditingHandler();
