<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.supplier.command_handler.remove_all_associated_product_suppliers_handler' shared service.

return $this->services['prestashop.adapter.product.supplier.command_handler.remove_all_associated_product_suppliers_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Supplier\CommandHandler\RemoveAllAssociatedProductSuppliersHandler(${($_ = isset($this->services['prestashop.adapter.product.update.product_supplier_updater']) ? $this->services['prestashop.adapter.product.update.product_supplier_updater'] : $this->load('getPrestashop_Adapter_Product_Update_ProductSupplierUpdaterService.php')) && false ?: '_'});
