<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.attribute_group.position_definition' shared service.

return $this->services['prestashop.core.grid.attribute_group.position_definition'] = new \PrestaShop\PrestaShop\Core\Grid\Position\PositionDefinition('attribute_group', 'id_attribute_group', 'position');
