<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.feature.command_handler.edit_feature_handler' shared service.

return $this->services['prestashop.adapter.feature.command_handler.edit_feature_handler'] = new \PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\EditFeatureHandler();
