<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.updater.product_tag_updater' shared service.

return $this->services['prestashop.adapter.product.updater.product_tag_updater'] = new \PrestaShop\PrestaShop\Adapter\Product\Update\ProductTagUpdater(${($_ = isset($this->services['prestashop.adapter.product.repository.tag_repository']) ? $this->services['prestashop.adapter.product.repository.tag_repository'] : ($this->services['prestashop.adapter.product.repository.tag_repository'] = new \PrestaShop\PrestaShop\Adapter\Product\Repository\TagRepository())) && false ?: '_'});
