<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.zone.query_handler.get_zone_for_editing_handler' shared service.

return $this->services['prestashop.adapter.zone.query_handler.get_zone_for_editing_handler'] = new \PrestaShop\PrestaShop\Adapter\Zone\QueryHandler\GetZoneForEditingHandler();
