<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order_message.query_handler.get_order_message_for_editing_handler' shared service.

return $this->services['prestashop.adapter.order_message.query_handler.get_order_message_for_editing_handler'] = new \PrestaShop\PrestaShop\Adapter\OrderMessage\QueryHandler\GetOrderMessageForEditingHandler();
