<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order_return_state.command_handler.edit_order_return_state_handler' shared service.

return $this->services['prestashop.adapter.order_return_state.command_handler.edit_order_return_state_handler'] = new \PrestaShop\PrestaShop\Adapter\OrderReturnState\CommandHandler\EditOrderReturnStateHandler();
