<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Admin\ProductImageController' shared service.

$this->services['PrestaShopBundle\\Controller\\Admin\\ProductImageController'] = $instance = new \PrestaShopBundle\Controller\Admin\ProductImageController();

$instance->setContainer($this);

return $instance;
