<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'prestashop.module.blockwishlist.grid.all_time_statistics_data_factory' shared service.

return $this->services['prestashop.module.blockwishlist.grid.all_time_statistics_data_factory'] = new \PrestaShop\Module\BlockWishList\Grid\Data\AllTimeStatisticsGridDataFactory(${($_ = isset($this->services['doctrine.cache.provider']) ? $this->services['doctrine.cache.provider'] : ($this->services['doctrine.cache.provider'] = new \Doctrine\Common\Cache\FilesystemCache(($this->targetDirs[0].'/doctrine')))) && false ?: '_'}, ${($_ = isset($this->services['prestashop.module.blockwishlist.calculator.statistics_calculator']) ? $this->services['prestashop.module.blockwishlist.calculator.statistics_calculator'] : $this->load('getPrestashop_Module_Blockwishlist_Calculator_StatisticsCalculatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.shop.context']) ? $this->services['prestashop.adapter.shop.context'] : ($this->services['prestashop.adapter.shop.context'] = new \PrestaShop\PrestaShop\Adapter\Shop\Context())) && false ?: '_'}->getContextShopID());
