<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.order.command_handler.generate_invoice_handler' shared service.

return $this->services['prestashop.adapter.order.command_handler.generate_invoice_handler'] = new \PrestaShop\PrestaShop\Adapter\Order\CommandHandler\GenerateInvoiceHandler();
