<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.address.query_handler.get_required_fields_for_address' shared service.

return $this->services['prestashop.adapter.address.query_handler.get_required_fields_for_address'] = new \PrestaShop\PrestaShop\Adapter\Address\QueryHandler\GetRequiredFieldsForAddressHandler();
