<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.pack.command_handler.get_packed_products_handler' shared service.

return $this->services['prestashop.adapter.product.pack.command_handler.get_packed_products_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\Pack\QueryHandler\GetPackedProductsHandler(${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'}->getInt("PS_LANG_DEFAULT"));
