<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.image.product_image_filesystem_path_factory' shared service.

return $this->services['prestashop.adapter.product.image.product_image_filesystem_path_factory'] = new \PrestaShop\PrestaShop\Adapter\Product\Image\ProductImagePathFactory(($this->targetDirs[3].'/img/p/'), ($this->targetDirs[3].'/img/tmp/'), ${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getContext()->language->iso_code);
