<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.mail_template.partial_template_renderer' shared service.

return $this->services['prestashop.adapter.mail_template.partial_template_renderer'] = new \PrestaShop\PrestaShop\Adapter\MailTemplate\MailPartialTemplateRenderer(${($_ = isset($this->services['prestashop.adapter.legacy.context']) ? $this->services['prestashop.adapter.legacy.context'] : $this->getPrestashop_Adapter_Legacy_ContextService()) && false ?: '_'}->getSmarty());
