<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.address.command_handler.edit_cart_address_handler' shared service.

return $this->services['prestashop.adapter.address.command_handler.edit_cart_address_handler'] = new \PrestaShop\PrestaShop\Adapter\Address\CommandHandler\EditCartAddressHandler(${($_ = isset($this->services['prestashop.adapter.address.command_handler.edit_customer_address_handler']) ? $this->services['prestashop.adapter.address.command_handler.edit_customer_address_handler'] : ($this->services['prestashop.adapter.address.command_handler.edit_customer_address_handler'] = new \PrestaShop\PrestaShop\Adapter\Address\CommandHandler\EditCustomerAddressHandler())) && false ?: '_'});
