<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.credit_slip.credit_slip_options.configuration' shared service.

return $this->services['prestashop.core.credit_slip.credit_slip_options.configuration'] = new \PrestaShop\PrestaShop\Core\CreditSlip\CreditSlipOptionsConfiguration(${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : ($this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())) && false ?: '_'});
