<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.product.attribute_group.query_handler.get_product_attribute_groups_handler' shared service.

return $this->services['prestashop.adapter.product.attribute_group.query_handler.get_product_attribute_groups_handler'] = new \PrestaShop\PrestaShop\Adapter\Product\AttributeGroup\QueryHandler\GetProductAttributeGroupsHandler(${($_ = isset($this->services['prestashop.core.admin.attribute_group.repository']) ? $this->services['prestashop.core.admin.attribute_group.repository'] : $this->load('getPrestashop_Core_Admin_AttributeGroup_RepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.attribute.repository.attribute_repository']) ? $this->services['prestashop.adapter.attribute.repository.attribute_repository'] : $this->load('getPrestashop_Adapter_Attribute_Repository_AttributeRepositoryService.php')) && false ?: '_'});
