<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.bundle.form.validator.constraints.tiny_mce_max_length_validator' shared service.

return $this->services['prestashop.bundle.form.validator.constraints.tiny_mce_max_length_validator'] = new \PrestaShopBundle\Form\Validator\Constraints\TinyMceMaxLengthValidator(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
