<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.image.image_generator' shared service.

return $this->services['prestashop.adapter.image.image_generator'] = new \PrestaShop\PrestaShop\Adapter\Image\ImageGenerator();
