<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.image.position_definition' shared service.

return $this->services['prestashop.core.grid.image.position_definition'] = new \PrestaShop\PrestaShop\Core\Grid\Position\PositionDefinition('image', 'id_image', 'position', 'id_product', 1);
