<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.grid.action.row.accessibility_checker.print_delivery_slip' shared service.

return $this->services['prestashop.core.grid.action.row.accessibility_checker.print_delivery_slip'] = new \PrestaShop\PrestaShop\Core\Grid\Action\Row\AccessibilityChecker\PrintDeliverySlipAccessibilityChecker();
