<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.updater.paypal.account' shared service.

return $this->services['ps_checkout.updater.paypal.account'] = new \PrestaShop\Module\PrestashopCheckout\Updater\PaypalAccountUpdater(${($_ = isset($this->services['ps_checkout.persistent.configuration']) ? $this->services['ps_checkout.persistent.configuration'] : $this->load('getPsCheckout_Persistent_ConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.paypal.provider.merchant_integration']) ? $this->services['ps_checkout.paypal.provider.merchant_integration'] : $this->load('getPsCheckout_Paypal_Provider_MerchantIntegrationService.php')) && false ?: '_'});
