<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Admin\SupplierController' shared service.

$this->services['PrestaShopBundle\\Controller\\Admin\\SupplierController'] = $instance = new \PrestaShopBundle\Controller\Admin\SupplierController();

$instance->setContainer($this);

return $instance;
