<?php

namespace Proxies\__CG__\PrestaShop\Module\ProductComment\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProductComment extends \PrestaShop\Module\ProductComment\Entity\ProductComment implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'id', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'productId', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'customerId', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'guestId', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'customerName', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'title', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'content', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'grade', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'validate', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'deleted', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'dateAdd'];
        }

        return ['__isInitialized__', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'id', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'productId', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'customerId', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'guestId', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'customerName', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'title', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'content', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'grade', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'validate', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'deleted', '' . "\0" . 'PrestaShop\\Module\\ProductComment\\Entity\\ProductComment' . "\0" . 'dateAdd'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProductComment $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getProductId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductId', []);

        return parent::getProductId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductId($productId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductId', [$productId]);

        return parent::setProductId($productId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerId', []);

        return parent::getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerId($customerId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerId', [$customerId]);

        return parent::setCustomerId($customerId);
    }

    /**
     * {@inheritDoc}
     */
    public function getGuestId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuestId', []);

        return parent::getGuestId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGuestId($guestId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGuestId', [$guestId]);

        return parent::setGuestId($guestId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerName', []);

        return parent::getCustomerName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerName($customerName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerName', [$customerName]);

        return parent::setCustomerName($customerName);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContent', []);

        return parent::getContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setContent($content)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContent', [$content]);

        return parent::setContent($content);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrade', []);

        return parent::getGrade();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrade($grade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrade', [$grade]);

        return parent::setGrade($grade);
    }

    /**
     * {@inheritDoc}
     */
    public function isValidate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isValidate', []);

        return parent::isValidate();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidate($validate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidate', [$validate]);

        return parent::setValidate($validate);
    }

    /**
     * {@inheritDoc}
     */
    public function isDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeleted', []);

        return parent::isDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', [$deleted]);

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAdd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAdd', []);

        return parent::getDateAdd();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAdd($dateAdd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAdd', [$dateAdd]);

        return parent::setDateAdd($dateAdd);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

}
